### ISSUE TITLE
wher credits!!!

### ISSUE THREAD

**Issue by SmallPP420** [usrDottik/Meme-Downloader-2016#1]
pls make ios gsi for samsung s2 and overclocking kernel to 4ghz poco edition pls

**Comment by usrDottik** [comment]
I have not enough skill for that 😔

**Comment by SmallPP420** [comment]
but u said you'd give credits for original source and idea :pensive:

**Comment by SmallPP420** [comment]
im going to commit die now

**Comment by usrDottik** [comment]
Yee
I'm doinn it!

**Comment by SmallPP420** [comment]
thnaks for credits i undied :))))
